services:
  owrx:
    build: .
    container_name: openwebrxplus-softmbe
    restart: unless-stopped
    ports:
      - '8073:8073'
      - '5678:5678'
    environment:
      RU: Europe/Kirov
      FORWARD_LOCALPORT_1234: 5678
      OPENWEBRX_ADMIN_USER: admin
      OPENWEBRX_ADMIN_PASSWORD: admin
      HEALTHCHECK_USB_0BDA_2838: 1
      # HEALTHCHECK_USB_0BDA_2832: 1
      # HEALTHCHECK_USB_1DF7_3000: 1
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /opt/owrx-docker/etc:/etc/openwebrx
      - /opt/owrx-docker/var:/var/lib/openwebrx
      - /opt/owrx-docker/plugins:/usr/lib/python3/dist-packages/htdocs/plugins

# if you want your container to restart automatically if the HEALTHCHECK fails
# (see here: https://stackoverflow.com/a/48538213/420585)
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

